/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./explorer_bff.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface OverviewDTO {
    generated_at_ns: bigint;
    cache_age_ms: bigint;
    recent_activity: Array<EventRowDTO>;
    health: HealthSummaryDTO;
}
export interface EventDetailDTO {
    timestamp_ns: bigint;
    source: string;
    source_event_id: bigint;
    kind: string;
    global_id: string;
    generated_at_ns: bigint;
    payload_summary: string;
    related_event_ids: Array<string>;
    payload_json: string;
}
export interface ActivityCursor {
    page_size: number;
    before_global_id?: string;
}
export interface InitArgs {
    admin?: Principal;
    main: Principal;
    secondary?: Principal;
}
export interface HealthSummaryDTO {
    source_lag_seconds: bigint;
    generated_at_ns: bigint;
    level: HealthLevel;
    any_error: boolean;
    message: string;
}
export interface ActivityFeedDTO {
    filters_applied: ActivityFilter;
    events: Array<EventRowDTO>;
    next_cursor?: string;
    total_estimated: bigint;
}
export interface EventRowDTO {
    primary_principal?: Principal;
    timestamp_ns: bigint;
    primary_amount?: FormattedNumber;
    source: string;
    source_event_id: bigint;
    kind: string;
    global_id: string;
    approximate: boolean;
    payload_summary: string;
    secondary_principal?: Principal;
}
export interface FormattedNumber {
    raw_e8s: bigint;
    decimals: number;
    formatted: string;
}
export interface EntityDTO {
    id: string;
    kind: string;
    recent_events: Array<EventRowDTO>;
    generated_at_ns: bigint;
    display_label: string;
}
export interface ActivityFilter {
    to_ns?: bigint;
    types?: Array<string>;
    from_ns?: bigint;
    sources?: Array<string>;
    filter_principal?: Principal;
}
export type SetSourceResult = {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
};
export enum HealthLevel {
    Red = "Red",
    Yellow = "Yellow",
    Green = "Green"
}
export interface explorer_bffInterface {
    get_activity(arg0: ActivityFilter, arg1: ActivityCursor): Promise<ActivityFeedDTO>;
    get_entity(arg0: string, arg1: string): Promise<EntityDTO>;
    get_event(arg0: string): Promise<EventDetailDTO>;
    get_health(): Promise<HealthSummaryDTO>;
    get_overview(): Promise<OverviewDTO>;
    get_source_canisters(): Promise<{
        main: Principal;
        secondary?: Principal;
    }>;
    ping(): Promise<string>;
    set_source_canister(arg0: string, arg1: Principal): Promise<SetSourceResult>;
}
import type { ActivityCursor as _ActivityCursor, ActivityFeedDTO as _ActivityFeedDTO, ActivityFilter as _ActivityFilter, EntityDTO as _EntityDTO, EventRowDTO as _EventRowDTO, FormattedNumber as _FormattedNumber, HealthLevel as _HealthLevel, HealthSummaryDTO as _HealthSummaryDTO, OverviewDTO as _OverviewDTO, SetSourceResult as _SetSourceResult } from "./explorer_bff.did";
export class Explorer_bff implements explorer_bffInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_activity(arg0: ActivityFilter, arg1: ActivityCursor): Promise<ActivityFeedDTO> {
        const result = await this.actor.get_activity(to_candid_ActivityFilter_n1(arg0), to_candid_ActivityCursor_n3(arg1));
        return from_candid_ActivityFeedDTO_n5(result);
    }
    async get_entity(arg0: string, arg1: string): Promise<EntityDTO> {
        const result = await this.actor.get_entity(arg0, arg1);
        return from_candid_EntityDTO_n17(result);
    }
    async get_event(arg0: string): Promise<EventDetailDTO> {
        const result = await this.actor.get_event(arg0);
        return result;
    }
    async get_health(): Promise<HealthSummaryDTO> {
        const result = await this.actor.get_health();
        return from_candid_HealthSummaryDTO_n19(result);
    }
    async get_overview(): Promise<OverviewDTO> {
        const result = await this.actor.get_overview();
        return from_candid_OverviewDTO_n23(result);
    }
    async get_source_canisters(): Promise<{
        main: Principal;
        secondary?: Principal;
    }> {
        const result = await this.actor.get_source_canisters();
        return from_candid_record_n25(result);
    }
    async ping(): Promise<string> {
        const result = await this.actor.ping();
        return result;
    }
    async set_source_canister(arg0: string, arg1: Principal): Promise<SetSourceResult> {
        const result = await this.actor.set_source_canister(arg0, arg1);
        return from_candid_SetSourceResult_n26(result);
    }
}
function from_candid_ActivityFeedDTO_n5(value: _ActivityFeedDTO): ActivityFeedDTO {
    return from_candid_record_n6(value);
}
function from_candid_ActivityFilter_n7(value: _ActivityFilter): ActivityFilter {
    return from_candid_record_n8(value);
}
function from_candid_EntityDTO_n17(value: _EntityDTO): EntityDTO {
    return from_candid_record_n18(value);
}
function from_candid_EventRowDTO_n13(value: _EventRowDTO): EventRowDTO {
    return from_candid_record_n14(value);
}
function from_candid_HealthLevel_n21(value: _HealthLevel): HealthLevel {
    return from_candid_variant_n22(value);
}
function from_candid_HealthSummaryDTO_n19(value: _HealthSummaryDTO): HealthSummaryDTO {
    return from_candid_record_n20(value);
}
function from_candid_OverviewDTO_n23(value: _OverviewDTO): OverviewDTO {
    return from_candid_record_n24(value);
}
function from_candid_SetSourceResult_n26(value: _SetSourceResult): SetSourceResult {
    return from_candid_variant_n27(value);
}
function from_candid_opt_n10(value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(value: [] | [_FormattedNumber]): FormattedNumber | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(value: {
    primary_principal: [] | [Principal];
    timestamp_ns: bigint;
    primary_amount: [] | [_FormattedNumber];
    source: string;
    source_event_id: bigint;
    kind: string;
    global_id: string;
    approximate: boolean;
    payload_summary: string;
    secondary_principal: [] | [Principal];
}): {
    primary_principal?: Principal;
    timestamp_ns: bigint;
    primary_amount?: FormattedNumber;
    source: string;
    source_event_id: bigint;
    kind: string;
    global_id: string;
    approximate: boolean;
    payload_summary: string;
    secondary_principal?: Principal;
} {
    return {
        primary_principal: record_opt_to_undefined(from_candid_opt_n11(value.primary_principal)),
        timestamp_ns: value.timestamp_ns,
        primary_amount: record_opt_to_undefined(from_candid_opt_n15(value.primary_amount)),
        source: value.source,
        source_event_id: value.source_event_id,
        kind: value.kind,
        global_id: value.global_id,
        approximate: value.approximate,
        payload_summary: value.payload_summary,
        secondary_principal: record_opt_to_undefined(from_candid_opt_n11(value.secondary_principal))
    };
}
function from_candid_record_n18(value: {
    id: string;
    kind: string;
    recent_events: Array<_EventRowDTO>;
    generated_at_ns: bigint;
    display_label: string;
}): {
    id: string;
    kind: string;
    recent_events: Array<EventRowDTO>;
    generated_at_ns: bigint;
    display_label: string;
} {
    return {
        id: value.id,
        kind: value.kind,
        recent_events: from_candid_vec_n12(value.recent_events),
        generated_at_ns: value.generated_at_ns,
        display_label: value.display_label
    };
}
function from_candid_record_n20(value: {
    source_lag_seconds: bigint;
    generated_at_ns: bigint;
    level: _HealthLevel;
    any_error: boolean;
    message: string;
}): {
    source_lag_seconds: bigint;
    generated_at_ns: bigint;
    level: HealthLevel;
    any_error: boolean;
    message: string;
} {
    return {
        source_lag_seconds: value.source_lag_seconds,
        generated_at_ns: value.generated_at_ns,
        level: from_candid_HealthLevel_n21(value.level),
        any_error: value.any_error,
        message: value.message
    };
}
function from_candid_record_n24(value: {
    generated_at_ns: bigint;
    cache_age_ms: bigint;
    recent_activity: Array<_EventRowDTO>;
    health: _HealthSummaryDTO;
}): {
    generated_at_ns: bigint;
    cache_age_ms: bigint;
    recent_activity: Array<EventRowDTO>;
    health: HealthSummaryDTO;
} {
    return {
        generated_at_ns: value.generated_at_ns,
        cache_age_ms: value.cache_age_ms,
        recent_activity: from_candid_vec_n12(value.recent_activity),
        health: from_candid_HealthSummaryDTO_n19(value.health)
    };
}
function from_candid_record_n25(value: {
    main: Principal;
    secondary: [] | [Principal];
}): {
    main: Principal;
    secondary?: Principal;
} {
    return {
        main: value.main,
        secondary: record_opt_to_undefined(from_candid_opt_n11(value.secondary))
    };
}
function from_candid_record_n6(value: {
    filters_applied: _ActivityFilter;
    events: Array<_EventRowDTO>;
    next_cursor: [] | [string];
    total_estimated: bigint;
}): {
    filters_applied: ActivityFilter;
    events: Array<EventRowDTO>;
    next_cursor?: string;
    total_estimated: bigint;
} {
    return {
        filters_applied: from_candid_ActivityFilter_n7(value.filters_applied),
        events: from_candid_vec_n12(value.events),
        next_cursor: record_opt_to_undefined(from_candid_opt_n16(value.next_cursor)),
        total_estimated: value.total_estimated
    };
}
function from_candid_record_n8(value: {
    to_ns: [] | [bigint];
    types: [] | [Array<string>];
    from_ns: [] | [bigint];
    sources: [] | [Array<string>];
    filter_principal: [] | [Principal];
}): {
    to_ns?: bigint;
    types?: Array<string>;
    from_ns?: bigint;
    sources?: Array<string>;
    filter_principal?: Principal;
} {
    return {
        to_ns: record_opt_to_undefined(from_candid_opt_n9(value.to_ns)),
        types: record_opt_to_undefined(from_candid_opt_n10(value.types)),
        from_ns: record_opt_to_undefined(from_candid_opt_n9(value.from_ns)),
        sources: record_opt_to_undefined(from_candid_opt_n10(value.sources)),
        filter_principal: record_opt_to_undefined(from_candid_opt_n11(value.filter_principal))
    };
}
function from_candid_variant_n22(value: {
    Red: null;
} | {
    Yellow: null;
} | {
    Green: null;
}): HealthLevel {
    return "Red" in value ? HealthLevel.Red : "Yellow" in value ? HealthLevel.Yellow : "Green" in value ? HealthLevel.Green : value;
}
function from_candid_variant_n27(value: {
    Ok: null;
} | {
    Err: string;
}): {
    __kind__: "Ok";
    Ok: null;
} | {
    __kind__: "Err";
    Err: string;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: value.Err
    } : value;
}
function from_candid_vec_n12(value: Array<_EventRowDTO>): Array<EventRowDTO> {
    return value.map((x)=>from_candid_EventRowDTO_n13(x));
}
function to_candid_ActivityCursor_n3(value: ActivityCursor): _ActivityCursor {
    return to_candid_record_n4(value);
}
function to_candid_ActivityFilter_n1(value: ActivityFilter): _ActivityFilter {
    return to_candid_record_n2(value);
}
function to_candid_record_n2(value: {
    to_ns?: bigint;
    types?: Array<string>;
    from_ns?: bigint;
    sources?: Array<string>;
    filter_principal?: Principal;
}): {
    to_ns: [] | [bigint];
    types: [] | [Array<string>];
    from_ns: [] | [bigint];
    sources: [] | [Array<string>];
    filter_principal: [] | [Principal];
} {
    return {
        to_ns: value.to_ns ? candid_some(value.to_ns) : candid_none(),
        types: value.types ? candid_some(value.types) : candid_none(),
        from_ns: value.from_ns ? candid_some(value.from_ns) : candid_none(),
        sources: value.sources ? candid_some(value.sources) : candid_none(),
        filter_principal: value.filter_principal ? candid_some(value.filter_principal) : candid_none()
    };
}
function to_candid_record_n4(value: {
    page_size: number;
    before_global_id?: string;
}): {
    page_size: number;
    before_global_id: [] | [string];
} {
    return {
        page_size: value.page_size,
        before_global_id: value.before_global_id ? candid_some(value.before_global_id) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Explorer_bff {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Explorer_bff(actor);
}
