/* eslint-disable */

// This file was automatically generated by @icp-sdk/bindgen@0.3.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { Principal } from '@icp-sdk/core/principal';
import { IDL } from '@icp-sdk/core/candid';

export interface ActivityCursor {
  'page_size' : number,
  'before_global_id' : [] | [string],
}
export interface ActivityFeedDTO {
  'filters_applied' : ActivityFilter,
  'events' : Array<EventRowDTO>,
  'next_cursor' : [] | [string],
  'total_estimated' : bigint,
}
export interface ActivityFilter {
  'to_ns' : [] | [bigint],
  'types' : [] | [Array<string>],
  'from_ns' : [] | [bigint],
  'sources' : [] | [Array<string>],
  'filter_principal' : [] | [Principal],
}
export interface EntityDTO {
  'id' : string,
  'kind' : string,
  'recent_events' : Array<EventRowDTO>,
  'generated_at_ns' : bigint,
  'display_label' : string,
}
export interface EventDetailDTO {
  'timestamp_ns' : bigint,
  'source' : string,
  'source_event_id' : bigint,
  'kind' : string,
  'global_id' : string,
  'generated_at_ns' : bigint,
  'payload_summary' : string,
  'related_event_ids' : Array<string>,
  'payload_json' : string,
}
export interface EventRowDTO {
  'primary_principal' : [] | [Principal],
  'timestamp_ns' : bigint,
  'primary_amount' : [] | [FormattedNumber],
  'source' : string,
  'source_event_id' : bigint,
  'kind' : string,
  'global_id' : string,
  'approximate' : boolean,
  'payload_summary' : string,
  'secondary_principal' : [] | [Principal],
}
export interface FormattedNumber {
  'raw_e8s' : bigint,
  'decimals' : number,
  'formatted' : string,
}
export type HealthLevel = { 'Red' : null } |
  { 'Yellow' : null } |
  { 'Green' : null };
export interface HealthSummaryDTO {
  'source_lag_seconds' : bigint,
  'generated_at_ns' : bigint,
  'level' : HealthLevel,
  'any_error' : boolean,
  'message' : string,
}
export interface InitArgs {
  'admin' : [] | [Principal],
  'main' : Principal,
  'secondary' : [] | [Principal],
}
export interface OverviewDTO {
  'generated_at_ns' : bigint,
  'cache_age_ms' : bigint,
  'recent_activity' : Array<EventRowDTO>,
  'health' : HealthSummaryDTO,
}
export type SetSourceResult = { 'Ok' : null } |
  { 'Err' : string };
export interface _SERVICE {
  'get_activity' : ActorMethod<
    [ActivityFilter, ActivityCursor],
    ActivityFeedDTO
  >,
  'get_entity' : ActorMethod<[string, string], EntityDTO>,
  'get_event' : ActorMethod<[string], EventDetailDTO>,
  'get_health' : ActorMethod<[], HealthSummaryDTO>,
  'get_overview' : ActorMethod<[], OverviewDTO>,
  'get_source_canisters' : ActorMethod<
    [],
    { 'main' : Principal, 'secondary' : [] | [Principal] }
  >,
  'ping' : ActorMethod<[], string>,
  'set_source_canister' : ActorMethod<[string, Principal], SetSourceResult>,
}
export const idlFactory: IDL.InterfaceFactory = ({ IDL }) => {
  const InitArgs = IDL.Record({
    'admin' : IDL.Opt(IDL.Principal),
    'main' : IDL.Principal,
    'secondary' : IDL.Opt(IDL.Principal),
  });
  const ActivityFilter = IDL.Record({
    'to_ns' : IDL.Opt(IDL.Nat64),
    'types' : IDL.Opt(IDL.Vec(IDL.Text)),
    'from_ns' : IDL.Opt(IDL.Nat64),
    'sources' : IDL.Opt(IDL.Vec(IDL.Text)),
    'filter_principal' : IDL.Opt(IDL.Principal),
  });
  const ActivityCursor = IDL.Record({
    'page_size' : IDL.Nat32,
    'before_global_id' : IDL.Opt(IDL.Text),
  });
  const FormattedNumber = IDL.Record({
    'raw_e8s' : IDL.Nat64,
    'decimals' : IDL.Nat8,
    'formatted' : IDL.Text,
  });
  const EventRowDTO = IDL.Record({
    'primary_principal' : IDL.Opt(IDL.Principal),
    'timestamp_ns' : IDL.Nat64,
    'primary_amount' : IDL.Opt(FormattedNumber),
    'source' : IDL.Text,
    'source_event_id' : IDL.Nat64,
    'kind' : IDL.Text,
    'global_id' : IDL.Text,
    'approximate' : IDL.Bool,
    'payload_summary' : IDL.Text,
    'secondary_principal' : IDL.Opt(IDL.Principal),
  });
  const ActivityFeedDTO = IDL.Record({
    'filters_applied' : ActivityFilter,
    'events' : IDL.Vec(EventRowDTO),
    'next_cursor' : IDL.Opt(IDL.Text),
    'total_estimated' : IDL.Nat64,
  });
  const EntityDTO = IDL.Record({
    'id' : IDL.Text,
    'kind' : IDL.Text,
    'recent_events' : IDL.Vec(EventRowDTO),
    'generated_at_ns' : IDL.Nat64,
    'display_label' : IDL.Text,
  });
  const EventDetailDTO = IDL.Record({
    'timestamp_ns' : IDL.Nat64,
    'source' : IDL.Text,
    'source_event_id' : IDL.Nat64,
    'kind' : IDL.Text,
    'global_id' : IDL.Text,
    'generated_at_ns' : IDL.Nat64,
    'payload_summary' : IDL.Text,
    'related_event_ids' : IDL.Vec(IDL.Text),
    'payload_json' : IDL.Text,
  });
  const HealthLevel = IDL.Variant({
    'Red' : IDL.Null,
    'Yellow' : IDL.Null,
    'Green' : IDL.Null,
  });
  const HealthSummaryDTO = IDL.Record({
    'source_lag_seconds' : IDL.Nat64,
    'generated_at_ns' : IDL.Nat64,
    'level' : HealthLevel,
    'any_error' : IDL.Bool,
    'message' : IDL.Text,
  });
  const OverviewDTO = IDL.Record({
    'generated_at_ns' : IDL.Nat64,
    'cache_age_ms' : IDL.Nat64,
    'recent_activity' : IDL.Vec(EventRowDTO),
    'health' : HealthSummaryDTO,
  });
  const SetSourceResult = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  
  return IDL.Service({
    'get_activity' : IDL.Func(
        [ActivityFilter, ActivityCursor],
        [ActivityFeedDTO],
        [],
      ),
    'get_entity' : IDL.Func([IDL.Text, IDL.Text], [EntityDTO], []),
    'get_event' : IDL.Func([IDL.Text], [EventDetailDTO], []),
    'get_health' : IDL.Func([], [HealthSummaryDTO], ['query']),
    'get_overview' : IDL.Func([], [OverviewDTO], ['query']),
    'get_source_canisters' : IDL.Func(
        [],
        [
          IDL.Record({
            'main' : IDL.Principal,
            'secondary' : IDL.Opt(IDL.Principal),
          }),
        ],
        ['query'],
      ),
    'ping' : IDL.Func([], [IDL.Text], ['query']),
    'set_source_canister' : IDL.Func(
        [IDL.Text, IDL.Principal],
        [SetSourceResult],
        [],
      ),
  });
};

export const init: (args: { IDL: typeof IDL }) => IDL.Type[] = ({ IDL }) => {
  const InitArgs = IDL.Record({
    'admin' : IDL.Opt(IDL.Principal),
    'main' : IDL.Principal,
    'secondary' : IDL.Opt(IDL.Principal),
  });
  
  return [InitArgs];
};
